language: go

go:
  - 1.5
  - 1.6

before_script:
  - cd $GOPATH
  - curl -L https://github.com/coreos/etcd/releases/download/v3.0.0/etcd-v3.0.0-linux-amd64.tar.gz -o etcd-v3.0.0-linux-amd64.tar.gz
  - tar xzvf etcd-v3.0.0-linux-amd64.tar.gz
  - cd etcd-v3.0.0-linux-amd64
  - ./etcd &
  - sleep 3s
  - cd $TRAVIS_BUILD_DIR

script: make test
