[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/coreos/etcd"
  branch = "master"

[[override]]
  name = "github.com/coreos/bbolt"
  version = "=v1.3.1-coreos.6"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "~1.4"

[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "1.12.0"

[[constraint]]
  name = "github.com/chzyer/readline"
  branch = "master"

[[constraint]]
  name = "github.com/pingcap/kvproto"
  branch = "master"

[[constraint]]
  name = "github.com/google/btree"
  branch = "master"

[[constraint]]
  name = "github.com/etcd-io/gofail"
  branch = "master"

[[override]]
  name = "github.com/BurntSushi/toml"
  revision = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
