# PD Configuration.

cluster-id = 0

name = "pd"
data-dir = "default.pd"

client-urls = "http://127.0.0.1:2379"
# if not set, use ${client-urls}
advertise-client-urls = ""

peer-urls = "http://127.0.0.1:2380"
# if not set, use ${peer-urls}
advertise-peer-urls = ""

initial-cluster = "pd=http://127.0.0.1:2380"
initial-cluster-state = "new"

addr = "127.0.0.1:1234" # deprecate later
# if not set, use ${addr}
# advertise-addr = "" # deprecate later 
http-addr = "127.0.0.1:9090" # deprecate later


lease = 3
log-level = "debug"
tso-save-interval = 2000
max-peer-count = 3


[balance]
min-capacity-used-ratio = 0.4
max-capacity-used-ratio = 0.9
max-leader-count = 10
max-sending-snap-count = 3
max-receiving-snap-count = 3
max-diff-score-fraction = 0.1
balance-interval = 30
max-balance-count = 16
max-balance-retry-per-loop = 10
max-balance-count-per-loop = 3
max-transfer-wait-count = 3
max-peer-down-duration = "30m"
max-store-down-duration = "10m"
