name: Release Check

on:
  pull_request:
    branches:
      - release
      - release-5.2

jobs:
  check_release_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and release branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check release version
        run: >
          ! (git diff --name-only --exit-code origin/release -- ./release-version)
          || (echo "Please update the release-version file" && false)
